services:
  chat:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    image: ms-chat
    container_name: ms-chat
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
  #Nginx Service
  ms-chat-nginx:
    build:
      context: .
      dockerfile: Dockerfile_Nginx
    image: ms-chat-nginx
    container_name: ms-chat-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/